### ISSUE TITLE
Fallback should work without defined AWS credentials

### ISSUE THREAD

**Issue by camilohollanda** [autolist/sekreto#96]
Trying to initialize rails without AWS credentials set will raise error:

```
/usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/aws-sdk-core/plugins/regional_endpoint.rb:55:in `after_initialize': No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
	from /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/seahorse/client/base.rb:81:in `block in after_initialize'
	from /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/seahorse/client/base.rb:80:in `each'
	from /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/seahorse/client/base.rb:80:in `after_initialize'
	from /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/seahorse/client/base.rb:24:in `initialize'
	from /usr/local/bundle/gems/aws-sdk-secretsmanager-1.42.0/lib/aws-sdk-secretsmanager/client.rb:335:in `initialize'
	from /usr/local/bundle/gems/aws-sdk-core-3.105.0/lib/seahorse/client/base.rb:102:in `new'
	from /usr/local/bundle/gems/sekreto-0.5.1/lib/sekreto/railtie.rb:14:in `block (2 levels) in <class:Railtie>'
	from /usr/local/bundle/gems/sekreto-0.5.1/lib/sekreto.rb:26:in `setup'
	from /usr/local/bundle/gems/sekreto-0.5.1/lib/sekreto/railtie.rb:13:in `block in <class:Railtie>'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/application.rb:96:in `inherited'
	from /app/config/application.rb:26:in `<module:SparkEcommerce>'
	from /app/config/application.rb:24:in `<top (required)>'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:92:in `require'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /usr/local/bundle/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from -e:1:in `<main>'
```

**Comment by camilohollanda** [comment]
https://github.com/autolist/sekreto/pull/97
